from django.apps import AppConfig


class DataerrorConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'dataerror'
